version: 2


jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            apt-get update
            apt-get install unzip wget awscli openssh-client curl -y
            wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
            unzip terraform_0.11.3_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Set Terraform S3 remote state
          command: |
            export EC2_NAME=$(sed -n 's/ec2_instance_name.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
            export REGION=$(sed -n 's/region.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
            chmod 755 .circleci/circleci_init.sh
            ./.circleci/circleci_init.sh
      - run:
          name: Terraform Deployment
          command: |
            terraform init
            terraform apply -auto-approve
            terraform output rds_endpoint > rds_endpoint.txt
            terraform output ec2_endpoint > ec2_endpoint.txt
            EC2_HOST="$(cat ec2_endpoint.txt)"
            echo "EC2 host - $EC2_HOST"
      - run:
          name: Chef Deployment
          command: |      
            EC2_HOST="$(cat ec2_endpoint.txt)"
            echo "Wait for 2 minutes until Chef is configured on the instance" && sleep 120
            while ! scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~; do echo "SSH failed, retrying..." && sleep 5; done;
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'chmod 755 chef_commands.sh && ./chef_commands.sh'
      - run:
          name: Check if WP application is available
          command: |
            EC2_HOST="$(cat ec2_endpoint.txt)"
            until $(curl -sSf http://$EC2_HOST > /dev/null); do sleep 5; done

# scp -o StrictHostKeyChecking=no rds_endpoint.txt chef_commands.sh ubuntu@$EC2_HOST:~
