version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install terraform
          command: |
            sudo apt-get install unzip
            wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64
            unzip terraform_0.11.3_linux_amd64
            sudo mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Run terraform
          command: terraform apply