version: 2


jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            apt-get update
            apt-get install unzip wget -y
            wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
            unzip terraform_0.11.3_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Set Terraform S3 remote state
          command: |
            export EC2_NAME=$(sed -n 's/ec2_instance_name.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
            export REGION=$(sed -n 's/region.*\(".*"\)/\1/p' terraform.tfvars | tr -d '"')
            chmod 755 .circleci/circleci_init.sh
            ./.circleci/circleci_init.sh
      - run:
          name: Run terraform
          command: |
            terraform init
            terraform apply -auto-approve
            terraform output rds_endpoint >> environment.txt
            terraform output ec2_endpoint >> environment.txt
      - run:
          name: Chef deployment
          command: |
            EC2_HOST="$(grep -i "ec2" environment.txt | cut -d' ' -f 3)"
            echo "EC2 host - $EC2_HOST"
            chmod 755 chef_commands.sh
            scp environment.txt ubuntu@$EC2_HOST:~
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST 'bash -s' < ./chef_commands.sh