version: 2


jobs:
  remote_state:
    docker:
      - image: cgswong/aws:latest
    steps:
      - checkout
      - run:
          name: Terraform S3 remote state
          command: |
            chmod +x .circleci/circleci_init.sh
            ./.circleci/circleci_init.sh

  terraform:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            apt-get update
            apt-get install unzip wget -y
            wget https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip
            unzip terraform_0.11.3_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform --version
      - run:
          name: Run terraform
          command: |
            terraform init
            terraform apply -auto-approve


workflows:
  version: 2
  remote_state-and-terraform:
    jobs:
      - remote_state
      - terraform:
          requires:
            - remote_state